ALTER TABLE "Listing"
  ADD COLUMN IF NOT EXISTS "maintenanceAmount" INTEGER,
  ADD COLUMN IF NOT EXISTS "miscCharges" TEXT,
  ADD COLUMN IF NOT EXISTS "amenities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
